//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DidiGharWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DidiGharDBEntities : DbContext
    {
        public DidiGharDBEntities()
            : base("name=DidiGharDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Pincode> Pincodes { get; set; }
        public virtual DbSet<RequestMap> RequestMaps { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RequestsStatu> RequestsStatus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SkillsMap> SkillsMaps { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SubService> SubServices { get; set; }
        public virtual DbSet<UserAddress> UserAddresses { get; set; }
        public virtual DbSet<UserAuth> UserAuths { get; set; }
        public virtual DbSet<UserFeedback> UserFeedbacks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ProvidersAuth> ProvidersAuths { get; set; }
    }
}
