//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DidiGharWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMap
    {
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> SubServices { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string Reason { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Service Service { get; set; }
        public virtual SubService SubService { get; set; }
    }
}
