//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DidiGharWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillsMap
    {
        public int Id { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> SubServiceId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual Service Service { get; set; }
        public virtual SubService SubService { get; set; }
    }
}
